# Site settings
title: Mateus Sobrinho
email: me@doubleweb.com.br
url: http://msobrinho.com/
description: "Eu me chamo Mateus Sobrinho sou Programdor, WebMaster com foco em SEO e Gamer nas horas vagas. Moro em Porto Alegre e Curso Ciência da Computação na PUCRS."
skills: "WebMaster - Programador PHP - Analísta SEO"
meta_author: Sobrinho Mateus

# Google webmaster tools
google_verify: UA-66446296-1

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Localização
  copyright: Mateus Sobrinho
  social: Social
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/chocsx
  - title: facebook
    url: http://facebook.com/chocsx
  - title: github
    url: http://github.com/chocsx

# Postal address (add as many lines as necessary)
address:
   - line: Porto Alegre, RS

# Credits content
credits: '<a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
